### ISSUE TITLE
Can't compile with esphome 2023.3.0 

### ISSUE THREAD

**Issue by LooMarcus** [johannyren/PowerDisplayESPHome#1]
Hi i cant compile after update to ESPHome 2023.3.0 see logs, tried to create a new device but same error?

`INFO Reading configuration /config/esphome/power.yaml...
INFO Detected timezone 'Europe/Stockholm'
INFO Generating C++ source...
INFO Compiling app...
Processing power-display-esphome (board: esp32dev; framework: arduino; platform: platformio/espressif32 @ 5.2.0)

HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch3
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
Dependency Graph
|-- AsyncTCP-esphome @ 1.2.2
|-- Preferences @ 2.0.0
|-- WiFi @ 2.0.0
|-- FS @ 2.0.0
|-- Update @ 2.0.0
|-- ESPAsyncWebServer-esphome @ 2.1.0
|   |-- AsyncTCP-esphome @ 1.2.2
|-- DNSServer @ 2.0.0
|-- ESPmDNS @ 2.0.0
|-- SPI @ 2.0.0
Compiling /data/power-display-esphome/.pioenvs/power-display-esphome/src/main.cpp.o
Archiving /data/power-display-esphome/.pioenvs/power-display-esphome/libf54/libPreferences.a
Compiling /data/power-display-esphome/.pioenvs/power-display-esphome/lib64d/WiFi/WiFiClient.cpp.o
Compiling /data/power-display-esphome/.pioenvs/power-display-esphome/lib64d/WiFi/WiFiGeneric.cpp.o
Compiling /data/power-display-esphome/.pioenvs/power-display-esphome/lib64d/WiFi/WiFiMulti.cpp.o
/config/esphome/power.yaml:271:1: error: expected '}' at end of input
In file included from src/main.cpp:68:
src/power_display.h:76:39: note: to match this '{'
 class PowerDisplay : public Component {
                                       ^
In file included from src/main.cpp:68:
src/power_display.h: In member function 'void PowerDisplay::WritePriceText(esphome::display::DisplayBuffer*, int, `int)':`
src/power_display.h:178:7: error: 'inRange' was not declared in this scope
   if (inRange(currentPrice, EXTREMELY_EXPENSIVE, 100)) {price = EXTREMELY_EXPENSIVE_TEXT;}
       ^~~~~~~
src/power_display.h: In member function 'esphome::Color PowerDisplay::PriceColour(float)':
src/power_display.h:291:7: error: 'inRange' was not declared in this scope
   if (inRange(nNewPrice, EXTREMELY_EXPENSIVE, 100)) {colour = COLOR_CSS_MAROON;}
       ^~~~~~~
src/power_display.h: In member function 'double PowerDisplay::CalculateAccumulatedCost(double, double)':
src/power_display.h:315:2: error: a function-definition is not allowed here before '{' token
  {
  ^
/config/esphome/power.yaml: In lambda function:
/config/esphome/power.yaml:228:55: error: expected ')' before ';' token
      powerDisplay->SetCurrentPower((id(import_el).state);                     // Use if not using any solar production
                                    ~                  ^
                                                       )
/config/esphome/power.yaml:234:21: error: 'class PowerDisplay' has no member named 'WriteDailyEnergy'; did you mean 'SetDailyEnergy'?
      powerDisplay->WriteDailyEnergy(id(consumption_today).state);
                     ^~~~~~~~~~~~~~~~
                     SetDailyEnergy
/config/esphome/power.yaml: At global scope:
/config/esphome/power.yaml:271:1: error: expected unqualified-id at end of input
*** [/data/power-display-esphome/.pioenvs/power-display-esphome/src/main.cpp.o] Error 1
========================== [FAILED] Took 8.71 seconds ==========================`

**Comment by johannyren** [comment]
Sorry, this was due to a bad commit of unfinished changes in power_display.h. Original version has been reverted.
